#
# azure-pipelines.yml
#
#  Copyright © 2019 Visualisierungsinstitut der Universität Stuttgart. Alle Rechte vorbehalten.
#

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    platform: 'x64'
    configuration: 'Release'
    clean: true
    msbuildArchitecture: 'x64'