#
# azure-pipelines.yml
#
# Copyright © 2019 Visualisierungsinstitut der Universität Stuttgart. Alle Rechte vorbehalten.
#

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  #vsVersion: '15.0'

steps:
- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'latestStable'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true
    msbuildArchitecture: 'x64'
    #vsVersion: '$(vsVersion)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**\mmpld.nuspec'
    configuration: '$(buildConfiguration)'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '4'
    patchVersion: '0'
    verbosityPack: 'Detailed'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'gci -r "$(Pipeline.Workspace)"'
    errorActionPreference: 'silentlyContinue'
